keyconfig_data = \
[("Screen",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.animation_step", {"type": 'TIMER0', "value": 'ANY', "any": True}, None),
    ("screen.region_blend", {"type": 'TIMERREGION', "value": 'ANY', "any": True}, None),
    ("screen.screen_full_area", {"type": 'SPACE', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area",
     {"type": 'SPACE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("use_hide_panels", True),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_UP', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.region_quadview", {"type": 'Q', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("screen.repeat_last", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("file.execute", {"type": 'RET', "value": 'PRESS'}, None),
    ("file.execute", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("file.cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "ctrl": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("render.render",
     {"type": 'F12', "value": 'PRESS'},
     {"properties":
      [("use_viewport", True),
       ],
      },
     ),
    ("render.render",
     {"type": 'F12', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("animation", True),
       ("use_viewport", True),
       ],
      },
     ),
    ("render.view_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("render.view_show", {"type": 'F11', "value": 'PRESS'}, None),
    ("render.play_rendered_anim", {"type": 'F11', "value": 'PRESS', "ctrl": True}, None),
    ("screen.redo_last", {"type": 'F9', "value": 'PRESS'}, None),
    ("screen.userpref_show", {"type": 'U', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ],
   },
  ),
 ("Frames",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.frame_offset",
     {"type": 'LEFT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'RIGHT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", True),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_LAST', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_FIRST', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("reverse", True),
       ],
      },
     ),
    ("screen.animation_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("screen.animation_cancel", {"type": 'MEDIA_STOP', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("3D View Generic",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_collections_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_cursor_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_views_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_shading_pie'),
       ],
      },
     ),
    ("machin3.clipping_toggle", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Extremes",onKeyExtremes'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Settings Menu,onKeyMenu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Direction",onKeyDirection'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Increase Falloff Size,onKeyMoreFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Decrease Falloff Size,onKeyLessFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle Unbind Curve,onKeyUnbind'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_collections_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_cursor_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_views_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_shading_pie'),
       ],
      },
     ),
    ("machin3.clipping_toggle", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Extremes",onKeyExtremes'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Settings Menu,onKeyMenu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Direction",onKeyDirection'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Increase Falloff Size,onKeyMoreFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Decrease Falloff Size,onKeyLessFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle Unbind Curve,onKeyUnbind'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_collections_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_cursor_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_views_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_shading_pie'),
       ],
      },
     ),
    ("machin3.clipping_toggle", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Extremes",onKeyExtremes'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Settings Menu,onKeyMenu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Direction",onKeyDirection'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Increase Falloff Size,onKeyMoreFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Decrease Falloff Size,onKeyLessFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle Unbind Curve,onKeyUnbind'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Extremes",onKeyExtremes'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Settings Menu,onKeyMenu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle "Use Direction",onKeyDirection'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Increase Falloff Size,onKeyMoreFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Decrease Falloff Size,onKeyLessFalloff'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'BMS,Toggle Unbind Curve,onKeyUnbind'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_collections_pie'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MACHIN3_MT_cursor_pie'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_views_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_shading_pie'),
       ],
      },
     ),
    ("machin3.clipping_toggle", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("wm.context_toggle",
     {"type": 'T', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.show_region_toolbar'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'N', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.show_region_ui'),
       ],
      },
     ),
    ],
   },
  ),
 ("Sculpt",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'NORMAL'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SMOOTH'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'SHOW'),
       ("area", 'INSIDE'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("action", 'HIDE'),
       ("area", 'INSIDE'),
       ],
      },
     ),
    ("paint.hide_show",
     {"type": 'H', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'SHOW'),
       ("area", 'ALL'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("level", 1),
       ("relative", True),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("level", -1),
       ("relative", True),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'VALUE'),
       ("value", 0.0),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.mask_lasso_gesture", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'scene.tool_settings.sculpt.show_mask'),
       ],
      },
     ),
    ("sculpt.dynamic_topology_toggle", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("sculpt.set_detail_size", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SCALE'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ROTATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'TRANSLATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("mode", 'SCALE'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ROTATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'DRAW'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'SMOOTH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'PINCH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'I', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'INFLATE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'GRAB'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'LAYER'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'FLATTEN'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'CLAY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'CREASE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'SNAKE_HOOK'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'MASK'),
       ("toggle", True),
       ("create_missing", True),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.stroke_method'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_angle_control'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_sculpt_context_menu'),
       ],
    "active":False,
      },
     ),
    ],
   },
  ),
 ("Object Non-modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_modes_pie'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'BACK_SLASH', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_modes_pie'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'EDIT'),
       ("toggle", True),
       ],
      },
     ),
    ("view3d.object_mode_pie_or_toggle", {"type": 'TAB', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Modes'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("pie_menu_name", 'ConvertSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Edge'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Vertex'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Face'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("pie_menu_name", 'EdgeSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Modes'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("pie_menu_name", 'ConvertSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Edge'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Vertex'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Face'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("pie_menu_name", 'EdgeSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Modes'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("pie_menu_name", 'ConvertSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Edge'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Vertex'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Face'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("pie_menu_name", 'EdgeSelection'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Modes'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Edge'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Vertex'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Face'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("bc.topbar_activate", {"type": 'W', "value": 'PRESS', "alt": True}, None),
    ("hops.bevel_helper", {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("hops.mirror_gizmo", {"type": 'X', "value": 'PRESS', "alt": True}, None),
    ("hops.mirror_mirror_z", {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_y", {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_x", {"type": 'X', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_ViewportSubmenu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_MaterialListMenu'),
       ],
      },
     ),
    ("hops.helper", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'HOPS_MT_MainMenu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'HOPS_MT_MainPie'),
       ],
    "active":False,
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Modes'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Edge'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Vertex'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Face'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", '3D View'),
       ],
      },
     ),
    ("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview_remove_from", {"type": 'M', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.rotate",
     {"type": 'TRACKPADPAN', "value": 'ANY'},
     {    "active":False,
      },
     ),
    ("view3d.rotate",
     {"type": 'MOUSEROTATE', "value": 'ANY'},
     {    "active":False,
      },
     ),
    ("view3d.move",
     {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True},
     {    "active":False,
      },
     ),
    ("view3d.zoom",
     {"type": 'TRACKPADZOOM', "value": 'ANY'},
     {    "active":False,
      },
     ),
    ("view3d.zoom",
     {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True},
     {    "active":False,
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'NORTH', "alt": True},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'SOUTH', "alt": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'EAST', "alt": True},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'WEST', "alt": True},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", False),
       ],
      },
     ),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo_context'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ("cycle", True),
       ],
    "active":False,
      },
     ),
    ],
   },
  ),
 ("View3D Gesture Circle",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("SELECT", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("DESELECT", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("NOP", {"type": 'LEFTMOUSE', "value": 'RELEASE', "any": True}, None),
    ("DESELECT", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("NOP", {"type": 'MIDDLEMOUSE', "value": 'RELEASE', "any": True}, None),
    ("SUBTRACT", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("SUBTRACT", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("ADD", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("ADD", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("SIZE", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ],
   },
  ),
 ("Image",
  {"space_type": 'IMAGE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'MACHIN3_MT_modes_pie'),
       ],
    "active":False,
      },
     ),
    ("image.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("image.view_all",
     {"type": 'HOME', "value": 'PRESS', "shift": True},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("image.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("image.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("image.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("image.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("image.view_zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("image.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("image.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("image.view_zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("image.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("image.sample", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("point", 'BLACK_POINT'),
       ],
      },
     ),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("point", 'WHITE_POINT'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'EDIT'),
       ("toggle", True),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 0),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 1),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 2),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 3),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 4),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 5),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 6),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 7),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 8),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("image.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("image.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ],
   },
  ),
 ("3D View Tool: Move",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("transform.translate",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
    "active":False,
      },
     ),
    ("view3d.select_box", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'AND'),
       ],
      },
     ),
    ],
   },
  ),
 ("3D View Tool: Rotate",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("transform.rotate",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
    "active":False,
      },
     ),
    ("view3d.select_box", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'AND'),
       ],
      },
     ),
    ],
   },
  ),
 ("3D View Tool: Scale",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("transform.resize",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
    "active":False,
      },
     ),
    ("view3d.select_box", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'AND'),
       ],
      },
     ),
    ],
   },
  ),
 ("Window",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.pme_user_pie_menu_call",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Pie Menu'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Import_Export'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'MACHIN3_MT_save_pie'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Pie Menu'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Import_Export'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'MACHIN3_MT_save_pie'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Pie Menu'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("pie_menu_name", 'Import_Export'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'MACHIN3_MT_save_pie'),
       ],
      },
     ),
    ("wm.pme_user_pie_menu_call",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Origin'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Window'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'MACHIN3_MT_save_pie'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_new'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'SCREEN_MT_user_menu'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F1', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'FILE_BROWSER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F2', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CLIP_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F3', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'NODE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F4', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CONSOLE'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F5', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'VIEW_3D'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F6', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'GRAPH_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F7', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'PROPERTIES'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F8', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'SEQUENCE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F9', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'OUTLINER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F10', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'IMAGE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F11', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'TEXT_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F12', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'DOPESHEET_EDITOR'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'NDOF_BUTTON_MENU', "value": 'PRESS'},
     {"properties":
      [("name", 'USERPREF_MT_ndof_settings'),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.1),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.90909094),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.5),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.6666667),
       ],
      },
     ),
    ("info.reports_display_update", {"type": 'TIMER_REPORT', "value": 'ANY', "any": True}, None),
    ("wm.doc_view_manual_ui_context", {"type": 'F1', "value": 'PRESS'}, None),
    ("wm.call_panel",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_PT_name'),
       ("keep_open", False),
       ],
      },
     ),
    ("wm.search_menu", {"type": 'F3', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'F4', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_MT_file_context_menu'),
       ],
      },
     ),
    ("wm.search_menu", {"type": 'SPACE', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Create'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Object Mode'),
       ],
      },
     ),
    ("machin3.align", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    ("machin3.mirror",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", False),
       ("use_z", True),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", True),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'X', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", True),
       ("use_y", False),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.focus", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Create'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Object Mode'),
       ],
      },
     ),
    ("machin3.align", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    ("machin3.mirror",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", False),
       ("use_z", True),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", True),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'X', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", True),
       ("use_y", False),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.focus", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Create'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Object Mode'),
       ],
      },
     ),
    ("machin3.align", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    ("machin3.mirror",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", False),
       ("use_z", True),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", True),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'X', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", True),
       ("use_y", False),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.focus", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Create'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Object Mode'),
       ],
      },
     ),
    ("object.modal_rad", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("machin3.select_decals", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("machin3.call_decal_operator", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("machin3.call_decal_pie", {"type": 'D', "value": 'PRESS'}, None),
    ("machin3.align",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {    "active":False,
      },
     ),
    ("machin3.mirror",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", False),
       ("use_z", True),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", False),
       ("use_y", True),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.mirror",
     {"type": 'X', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("use_x", True),
       ("use_y", False),
       ("use_z", False),
       ("init", True),
       ],
      },
     ),
    ("machin3.focus", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("hops.slash", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("wm.pme_user_pie_menu_call",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("pie_menu_name", 'Create'),
       ("invoke_mode", 'HOTKEY'),
       ("keymap", 'Object Mode'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ("confirm", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ("confirm", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.duplicate_move_linked", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("collection.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
    "active":False,
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_collection", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 1),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 2),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 3),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 4),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 5),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 6),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 7),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 8),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 9),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "any": True},
     {"properties":
      [("collection_index", 10),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.move'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.rotate'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale'),
       ],
      },
     ),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'MACHIN3_MT_align_pie'),
       ],
      },
     ),
    ("machin3.clean_up", {"type": 'THREE', "value": 'PRESS'}, None),
    ("machin3.smart_face", {"type": 'FOUR', "value": 'PRESS'}, None),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("sharp", True),
       ],
      },
     ),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("sharp", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("slideoverride", True),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'CONNECT'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'PATHS'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'CENTER'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'LAST'),
       ("slideoverride", False),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'MACHIN3_MT_align_pie'),
       ],
      },
     ),
    ("machin3.clean_up", {"type": 'THREE', "value": 'PRESS'}, None),
    ("machin3.smart_face", {"type": 'FOUR', "value": 'PRESS'}, None),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("sharp", True),
       ],
      },
     ),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("sharp", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("slideoverride", True),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'CONNECT'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'PATHS'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'CENTER'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'LAST'),
       ("slideoverride", False),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'MACHIN3_MT_align_pie'),
       ],
      },
     ),
    ("machin3.clean_up", {"type": 'THREE', "value": 'PRESS'}, None),
    ("machin3.smart_face", {"type": 'FOUR', "value": 'PRESS'}, None),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("sharp", True),
       ],
      },
     ),
    ("machin3.smart_edge",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("sharp", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("slideoverride", True),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'CONNECT'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'PATHS'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'CENTER'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'LAST'),
       ("slideoverride", False),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'MACHIN3_MT_align_pie'),
       ],
    "active":False,
      },
     ),
    ("machin3.clean_up", {"type": 'THREE', "value": 'PRESS'}, None),
    ("machin3.smart_face",
     {"type": 'FOUR', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("machin3.smart_edge", {"type": 'TWO', "value": 'PRESS'}, None),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("slideoverride", True),
       ],
    "active":False,
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'CONNECT'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'PATHS'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'CENTER'),
       ("slideoverride", False),
       ],
      },
     ),
    ("machin3.smart_vert",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 'MERGE'),
       ("mergetype", 'LAST'),
       ("slideoverride", False),
       ],
      },
     ),
    ("hops.edit_bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("hops.edit_bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("vertex_only", False),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("vertex_only", True),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("mesh.flip_normals", {"type": 'N', "value": 'PRESS', "alt": True}, None),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS'}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NONE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.move'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.rotate'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale'),
       ],
      },
     ),
    ],
   },
  ),
 ("3D View Tool: BoxCutter",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("bc.custom", {"type": 'C', "value": 'PRESS'}, None),
    ("bc.display_snap", {"type": 'OSKEY', "value": 'PRESS'}, None),
    ("bc.display_snap", {"type": 'LEFT_CTRL', "value": 'PRESS'}, None),
    ("bc.draw_shape",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("bc.draw_shape", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("bc.draw_shape", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("bc.draw_shape", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("bc.draw_shape", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("bc.draw_shape", {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "alt": True}, None),
    ("bc.draw_shape", {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True}, None),
    ("bc.draw_shape", {"type": 'EVT_TWEAK_L', "value": 'ANY', "alt": True}, None),
    ("bc.draw_shape", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("wm.call_panel",
     {"type": 'D', "value": 'RELEASE', "ctrl": True},
     {"properties":
      [("name", 'BC_PT_behavior'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'D', "value": 'PRESS'},
     {"properties":
      [("name", 'BC_MT_pie'),
       ],
      },
     ),
    ("view3d.cursor3d",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("orientation", 'GEOM'),
       ],
    "active":False,
      },
     ),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(os.path.splitext(os.path.basename(__file__))[0], keyconfig_data)
